In [1]:
# Dependencies
import numpy as np
import pandas as pd

In [2]:
file = "2015.csv"
df2015 = pd.read_csv(file)
df2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [3]:
df2015.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

In [4]:
df2015.insert(loc=1, column="year", value="2015")
df2015

,Country,year,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,2015,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,2015,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,2015,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,2015,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,2015,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,2015,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
154,Benin,2015,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
155,Syria,2015,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
156,Burundi,2015,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
157,Togo,2015,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [5]:
df2015_renamed = df2015.rename(columns={"Happiness Rank": "happiness_rank",
                                         "Happiness Score": "happiness_score",
                                         "Standard Error": "standard_error",
                                         "Economy (GDP per Capita)": "gpd_per_capita",
                                         "Health (Life Expectancy)": "life_expectancy",
                                         "Trust (Government Corruption)": "government_corruption",
                                         "Dystopia Residual": "dystopia_residual"
                                     })
df2015_renamed

,Country,year,Region,happiness_rank,happiness_score,standard_error,gpd_per_capita,Family,life_expectancy,Freedom,government_corruption,Generosity,dystopia_residual
0,Switzerland,2015,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,2015,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,2015,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,2015,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,2015,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,2015,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
154,Benin,2015,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
155,Syria,2015,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
156,Burundi,2015,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
157,Togo,2015,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [6]:
file = "2016.csv"
df2016 = pd.read_csv(file)
df2016.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [7]:
df2016.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

In [8]:
df2016.insert(loc=1, column="year", value="2016")
df2016

,Country,year,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,2016,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,2016,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,2016,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,2016,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,2016,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,2016,Sub-Saharan Africa,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,2016,Southern Asia,154,3.360,3.288,3.432,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,2016,Sub-Saharan Africa,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,2016,Middle East and Northern Africa,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,2016,Sub-Saharan Africa,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

In [9]:
df2016_renamed = df2016.rename(columns={"Happiness Rank": "happiness_rank",
                                         "Happiness Score": "happiness_score",
                                         "Standard Error": "standard_error",
                                         "Economy (GDP per Capita)": "gpd_per_capita",
                                         "Health (Life Expectancy)": "life_expectancy",
                                         "Trust (Government Corruption)": "government_corruption",
                                         "Dystopia Residual": "dystopia_residual"
                                     })
df2016_renamed

,Country,year,Region,happiness_rank,happiness_score,Lower Confidence Interval,Upper Confidence Interval,gpd_per_capita,Family,life_expectancy,Freedom,government_corruption,Generosity,dystopia_residual
0,Denmark,2016,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,2016,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,2016,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,2016,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,2016,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,2016,Sub-Saharan Africa,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,2016,Southern Asia,154,3.360,3.288,3.432,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,2016,Sub-Saharan Africa,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,2016,Middle East and Northern Africa,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,2016,Sub-Saharan Africa,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

In [10]:
file = "2017.csv"
df2017 = pd.read_csv(file)
df2017.head()
df2017.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],
      dtype='object')

In [11]:
df2017 = df2017.drop(columns=['Whisker.high','Whisker.low'])
df2017.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score',
       'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.',
       'Freedom', 'Generosity', 'Trust..Government.Corruption.',
       'Dystopia.Residual'],
      dtype='object')

In [12]:
df2017_renamed = df2017.rename(columns={'Happiness.Rank': "happiness_rank",
                       'Happiness.Score': "happiness_score",
                       'Economy..GDP.per.Capita.': "gpd_per_capita",
                       'Health..Life.Expectancy.': "life_expectancy",
                       'Trust..Government.Corruption.': "government_corruption",
                       'Dystopia.Residual': "dystopia_residual"
                      })

In [13]:
df2017.insert(loc=1, column="year", value="2017")
df2017

,Country,year,Happiness.Rank,Happiness.Score,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,2017,1,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2017,2,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,2017,3,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,2017,4,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,2017,5,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,2017,151,3.471,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
151,Syria,2017,152,3.462,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
152,Tanzania,2017,153,3.349,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
153,Burundi,2017,154,2.905,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
154,Central African Republic,2017,155,2.693,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

In [14]:
file = "2018.csv"
df2018 = pd.read_csv(file)
df2018.head()
df2018.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [15]:
df2018.insert(loc=1, column="year", value="2018")
df2018

,Overall rank,year,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,2018,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,2018,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,2018,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,2018,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,2018,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...
151,152,2018,Yemen,3.355,0.442,1.073,0.343,0.244,0.083,0.064
152,153,2018,Tanzania,3.303,0.455,0.991,0.381,0.481,0.270,0.097
153,154,2018,South Sudan,3.254,0.337,0.608,0.177,0.112,0.224,0.106
154,155,2018,Central African Republic,3.083,0.024,0.000,0.010,0.305,0.218,0.038
155,156,2018,Burundi,2.905,0.091,0.627,0.145,0.065,0.149,0.076

In [16]:

df2018_renamed = df2018.rename(columns= {'Overall rank': "happiness_rank", 
                                 'Country or region': "Country",
                                 'Score': "happiness_score",
                                 'GDP per capita': "gpd_per_capita",
                                 'Healthy life expectancy': "life_expectancy",
                                 'Freedom to make life choices': "Freedom",
                                 'Perceptions of corruption': "government_corruption"
                                })

In [17]:
df2018_renamed.columns

Index(['happiness_rank', 'year', 'Country', 'happiness_score',
       'gpd_per_capita', 'Social support', 'life_expectancy', 'Freedom',
       'Generosity', 'government_corruption'],
      dtype='object')

In [18]:
frames = [df2015_renamed, df2016_renamed, df2017_renamed, df2018_renamed]

result = pd.concat(frames)
result

,Country,year,Region,happiness_rank,happiness_score,standard_error,gpd_per_capita,Family,life_expectancy,Freedom,government_corruption,Generosity,dystopia_residual,Lower Confidence Interval,Upper Confidence Interval,Social support
0,Switzerland,2015,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,NaN,NaN,NaN
1,Iceland,2015,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,NaN,NaN,NaN
2,Denmark,2015,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,NaN,NaN,NaN
3,Norway,2015,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,NaN,NaN,NaN
4,Canada,2015,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,2018,NaN,152,3.355,NaN,0.44200,NaN,0.34300,0.24400,0.06400,0.08300,NaN,NaN,NaN,1.073
152,Tanzania,2018,NaN,153,3.303,NaN,0.45500,NaN,0.38100,0.48100,0.09700,0.27000,NaN,NaN,NaN,0.991
153,South Sudan,2018,NaN,154,3.254,NaN,0.33700,NaN,0.17700,0.11200,0.10600,0.22400,NaN,NaN,NaN,0.608
154,Central African Republic,2018,NaN,155,3.083,NaN,0.02400,NaN,0.01000,0.30500,0.03800,0.21800,NaN,NaN,NaN,0.000
155,Burundi,2018,NaN,156,2.905,NaN,0.09100,NaN,0.14500,0.06500,0.07600,0.14900,NaN,NaN,NaN,0.627

In [19]:
result = result.drop(columns=['Lower Confidence Interval', 'Upper Confidence Interval'])

In [20]:
result = result.fillna("")
result

,Country,year,Region,happiness_rank,happiness_score,standard_error,gpd_per_capita,Family,life_expectancy,Freedom,government_corruption,Generosity,dystopia_residual,Social support
0,Switzerland,2015,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,
1,Iceland,2015,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,
2,Denmark,2015,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,
3,Norway,2015,Western Europe,4,7.522,0.0388,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,
4,Canada,2015,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,2018,,152,3.355,,0.44200,,0.34300,0.24400,0.064,0.08300,,1.073
152,Tanzania,2018,,153,3.303,,0.45500,,0.38100,0.48100,0.097,0.27000,,0.991
153,South Sudan,2018,,154,3.254,,0.33700,,0.17700,0.11200,0.106,0.22400,,0.608
154,Central African Republic,2018,,155,3.083,,0.02400,,0.01000,0.30500,0.038,0.21800,,0.0
155,Burundi,2018,,156,2.905,,0.09100,,0.14500,0.06500,0.076,0.14900,,0.627

In [21]:
result.to_csv('clean_new.csv', index=False)